### ISSUE TITLE
Regel: Abgabe nur über Forks -> existierende Lösungen sind einsehbar

### ISSUE THREAD

**Issue by Syndesi** [zelosos/ReisenderChallenge#1]
Hi,

da Forks immer öffentlich sind, können existierende Lösungen anderer kopiert werden.
Dementsprechend kann man entweder GitHub zur Versionsverwaltung garnicht nutzen (was ich schade finde) oder man entwickelt anfangs in einem privatem Repo und kopiert die Änderungen am Ende manuell.
Dementsprechend würde ich gerne Wissen, welche Option man nutzen sollte.

**Comment by zelosos** [comment]
Hi,
ich würde zum Zweiten raten. Da man nur Code hinzufügen und nicht löschen darf, sollte ein Merge am Ende recht unkompliziert sein. Ich entwickel meine Lösung auch in einem privaten Repository.
Als Student ist ein privates Reposity nicht kostenpflichtig.
