### ISSUE TITLE
Fehler in der README und Frage zum Score

### ISSUE THREAD

**Issue by nitwhiz** [zelosos/ReisenderChallenge#2]
README Zeile 32 sollte 6 **Milli**sekunden sein. Zumindest sagt der Algorithmus das.

Damit einhergehend, auf welcher Skala bewegt sich der Score? Ab wann ist ein Score gut, wann ist er schlecht?
Der Algo zur Score-Errechnung wirkt recht wild und random, so unkommentiert wie er ist. Die Formel und ein Maximum wären schon genug. :)

**Comment by zelosos** [comment]
Mit der Zeit hast du recht. Passe ich an.

Der Score drückt aus, wie viel Prozent deine Route besser ist, als eine Zufällige.
Sprich eine zufällig gewählte Route gibt einen Score von 1,0. Da die verbleibende Zeit dazu addiert wird erhöht sich der Wert leicht. Eine zufällig gewählte Route erreicht etwa einen score von 11.

Mit meinen Tests habe ich einen Wert von 36.2992 erreicht. Dort ist aber noch Platz nach oben.
Wenn du also einen Score über 36 erreichst bist du auf dem richtigen Weg.
Um den maximal möglichen Score zu erreichen, müsstest du die Länge des kürzesten Weges kennen, was wiederum die Aufgabe ist ;)

**Comment by zelosos** [comment]
Danke für das ansprechen der Scorefunktion. Mir ist gerade aufgefallen, dass ich die nicht angepasst hatte.

Falls dich der Wert 0,521405433 wundert. Das ist ein Aproximationswert für den Abstand zweier zufällig platzierter Punkte in einem Quadrat der Seitenlänge 1.
