### ISSUE TITLE
Start != Ziel ist trotzdem eine korrekte Lösung

### ISSUE THREAD

**Issue by nitwhiz** [zelosos/ReisenderChallenge#3]
Das Path-Checking erkennt nicht, wenn der erste und der letzte Punkt in der Route nicht dieselben sind aka Start == Ziel. Das ist allerdings 'ne Prämisse des TSP und beeinflusst logischerweise die Länge des Pfades.

**Comment by zelosos** [comment]
Das ist korrekt. Ich wollte das ursprüngliche Problem etwas abändern, sodass man nicht direkt Lösungen aus wissenschaftlichen Paper übernehmen kann. Es kann somit sinnvoll sein einen anderen Startpunkt zu wählen. (siehe Tipps)

**Comment by nitwhiz** [comment]
Also sollte man trotzdem zum Startpunkt zurückkehren oder nicht?

**Comment by zelosos** [comment]
Nur, wenn du einen schlechteren Score haben möchtest.
